json.id product.id
json.name product.name
json.price product.price
json.stock product.stock
json.description product.description
json.created_at product.created_at
json.updated_at product.updated_at
json.supplier product.supplier
json.supplier_id product.supplier_id
json.images product.images